
import "./globals.css";
import Footer from "@/components/Footer/Footer";
import Navbar from "@/components/Navbar/Navbar";

export const metadata = {
  title: "PokeNext",
  description: "Generated by create next app",
  icons: {
    icon: '/favicon.ico', // Caminho correto para o favicon
    apple: '/apple-touch-icon.png', // Para dispositivos Apple
    shortcut: '/shortcut-icon.png', // Para atalhos
    other: '/other-icon.png',
  },
};

export default function RootLayout({ children }) {
  return (
    <html lang="pt-BR">
      <body>
        <Navbar />
        <main className="main-container">{children}</main>
        <Footer />
      </body>
    </html>
  );
}
